gateway:
  listenAddr: ":8080"
  routes:
    - name: "products"
      context: "/api/products/get"
      target: 
        addr: "http://localhost"
        context: "/api/products/get"
        port: 28841
    - name: "auth"
      context: "/auth"
      target: 
        addr: "http://localhost"
        context: /auth
        proxyPortHeader: "X-LBA-Version"
    - name: "sendCrash"
      context: "/sendCrash"
      target: 
        addr: "http://localhost"
        context: "/sendCrash"
        proxyPortHeader: "X-LBA-Version"
  aggregatedRoutes:
    # - name: "aggregatedTest"
    #   context: "/aggregateTest"
    #   targets:
    #     - target: 
    #       addr: http://localhost
    #       context: /api/test
    #       port: 28841
    #     - target: 
    #       addr: http://localhost
    #       context: /api/test2
    #       proxyPortHeader: "X-LBA-Version"
  chainedRoutes:
    - name: "validatePayment"
      context: "/validate"
      targets:
        - target: 
          addr: "http://localhost"
          context: "/api/validator/validate"
          port: 28841
        - target: 
          addr: "http://localhost"
          context: "/api/config/takePaymentReward"
          proxyPortHeader: "X-LBA-Version"
  groupRoutes:
  - name: "playerHub"
    contextPrifix: "/playerHub"
    target: 
      addr: http://localhost
      context:
      proxyPortHeader: X-LBA-Version